### ISSUE TITLE
The number of Crashes and ANRs has increased

### ISSUE THREAD

**Issue by ilakhin** [getsentry/sentry-java#2955]
### Environment

How do you use Sentry?
- Self-hosted 22.11.0, 23.2.0

Which version of the SDK?
- 1.2.0, 1.5.0

How did you install the package? (Git-URL, Assetstore)
- Git-URL

Which version of Unity?
- 2021.3.25f1, 2020.3.46f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
- Android

### Actual Result

Since September 11, the number of Crashes and ANRs has increased significantly.

### Any logs or screenshots

<img width="1326" alt="Screenshot at Sep 16 14-32-34" src="https://github.com/getsentry/sentry-unity/assets/3340145/c4f5c8aa-9633-4f86-9985-df7004b707ff">
<img width="1321" alt="Screenshot at Sep 16 14-29-08" src="https://github.com/getsentry/sentry-unity/assets/3340145/c617794d-06bd-40b7-8bec-34a3315e4cfc">

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1949) by [Unito](https://www.unito.io)

**Comment by markushi** [comment]
Quick update: We’re still investigating into this issue. Whilst we’re already able to reproduce the issue, we also see app crashes within various other native libraries (e.g. libhermes.so from RN, libbase.so from com.google.mainline.primary.libs, ...) on the same device, hinting that something is clearly wrong with the Google Play System update from August.

As an intermediate “solution” we added easy ways to disable `sentry-native`, but be aware that you might see other crashes instead then.
* For our Unity SDK, starting with version `1.6.0` there’s an option called “NDK integration” which allows you to disable `sentry-native`
* For our React Native SDK, starting with version `5.10.0` there’s now an `enableNdk` option which can be set to `false`
* For our Android SDK you can [follow our docs on how to disable `sentry-native` ](https://docs.sentry.io/platforms/android/configuration/using-ndk/#disable-ndk-integration)

**Comment by gnprice** [comment]
Thanks for the update. I appreciate the communication about your progress on the issue.

> Whilst we’re already able to reproduce the issue, we also see app crashes within various other native libraries (e.g. libhermes.so from RN, libbase.so from com.google.mainline.primary.libs, ...) on the same device, hinting that something is clearly wrong with the Google Play System update from August.

Are you seeing those crashes only when Sentry (`libsentry.so`) is also present? Or are you also seeing evidence of elevated crashes starting with that Google Play system update in apps that don't have `libsentry.so`?

If the former, then this unfortunately isn't evidence at all of the bug being in any of those libraries instead of in Sentry.

The symptoms look characteristic of a memory-corruption issue — meaning that some code within some native library is writing to a place in memory where it shouldn't, corrupting data belonging to other code. If there is a memory corruption bug in Sentry, then it's typical that the data it writes over would be data belonging to a variety of other native libraries in the app. That causes crashes where the stack traces are in a wide variety of areas of code, including libraries that have nothing to do with the bug — the code that's in the stack trace isn't the buggy code, but only some code that stumbled over the data corrupted by the bug.

It's possible that something is wrong with that Google Play system update. If you haven't already, I'd encourage you to try to engage with the Android folks at Google to share the information you have that points in that direction.

But it's also quite possible that (a) there is a memory corruption bug in Sentry which has been there all along, and (b) that Google Play system update simply causes that bug to get exercised more frequently.

> As an intermediate “solution” we added easy ways to disable `sentry-native`

Thanks. When disabling `sentry-native` in this way, can you tell us whether that causes `libsentry.so` to no longer be active in the app? Or is `libsentry.so` (or other native code from Sentry) still involved even when the events being reported aren't from native code?

**Comment by markushi** [comment]
> Are you seeing those crashes only when Sentry (libsentry.so) is also present? Or are you also seeing evidence of elevated crashes starting with that Google Play system update in apps that don't have libsentry.so?

Yes, we do see crashes where `libsentry.so` is not even loaded. Due to the nature of these crashes it's unclear if this has the same root cause or is entirely another issue - we're still looking into that.

We're already in contact with some Android folks at Google, but unfortunately I can't share any details in public. Rest assured, we feel your pain - this issue has top priority for us!

> When disabling sentry-native in this way, can you tell us whether that causes libsentry.so to no longer be active in the app?

Yes, this will prevent `libsentry.so` from being loaded, and thus no native calls being done from the SDK. The native SDK parts would still be packaged with your app, to avoid that can follow our [Android docs](https://docs.sentry.io/platforms/android/configuration/using-ndk/#disable-ndk-integration) on how to completely remove `sentry-native` from your builds.

**Comment by markushi** [comment]
If anyone can reproduce this issue locally, you can help us by providing crash-reports the following way:
1. Enable [GWP-Asan](https://developer.android.com/ndk/guides/gwp-asan) for your app
2. Reproduce the crash
3. run `adb bugreport crash.zip`
4. Send your `crash.zip` to markus.hintersteiner@sentry.io

**Comment by zbyhoo** [comment]
> As an intermediate “solution” we added easy ways to disable `sentry-native`

@markushi does this disable the whole Sentry functionality or issues reported from app logic will work?

**Comment by markushi** [comment]
> @markushi does this disable the whole Sentry functionality or issues reported from app logic will work?

Disabling `sentry-native` only affects native (e.g. C, C++) compilation units, any Java/Kotlin functionality will still work as usual.

**Comment by rschweter** [comment]
Any updates on this?

**Comment by TheRogue76** [comment]
I've updated to the latest version and set `enableNative` to false. While my Sentry dashboard has calmed down, my Google Play dashboard still reports an order of magnitude more significant crash rates that Sentry is seemingly not picking up. It feels like there is a lot more broken here

**Comment by chreck** [comment]
As mentioned in the comments above ([New package versions](https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1739030872), [How to setup](https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1739794046)) and in the [documentation](https://docs.sentry.io/platforms/android/configuration/using-ndk/#disable-ndk-integration), I will provide a brief summary here. Please feel free to provide feedback if anything is incorrect. This is the setup we have implemented in our project. We haven't disabled Sentry entirely; instead, we have disabled the Sentry Android NDK part. Here's the configuration for both React Native and an Android project.

# React Native

**package.json**

Update to the latest sentry react-native package.

`"@sentry/react-native": "^5.10.0",`


**AndroidManifest.xml**

Disable NDK by default, just to be sure it is inactive.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
   ...
    <application>
       ...
        <meta-data android:name="io.sentry.ndk.enable" android:value="false" />
    </application>
</manifest>
```

**Javascript/Typescript**

Disable NDK with the new option `enableNdk`.

```javascript
Sentry.init({
  dsn: "https://123456@sentry.io/100",
  enableNdk: false,
})
```

# Android project only

If you are using an Android project only, you can still use Sentry but disable the NDK part of sentry.

**AndroidManifest.xml**

Disable NDK by default

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
   ...
    <application>
       ...
        <meta-data android:name="io.sentry.ndk.enable" android:value="false" />
    </application>
</manifest>
```

**Comment by kahest** [comment]
@TheRogue76 could you provide some information about the crashes you see on Play Console? Please send to karl.struggl@sentry.io if you can 🙏

**Comment by TheRogue76** [comment]
> Fatal Exception: java.lang.ArrayIndexOutOfBoundsException software-mansion/react-native-reanimated#3856

Will do

**Comment by TheRogue76** [comment]
> karl.struggl@sentry.io

Hi @kahest. I have sent you an email with the logs. Let me know if it hasn't arrived.

**Comment by kahest** [comment]
Quick update:
- we see confirmation that these crashes also occur when Sentry is removed or Sentry NDK support is disabled via `enableNdk=false` - this means that while Sentry native support can be one cause of these issues, they are also caused by other native libraries, which hints at a more generic problem
- as a result of this, you might still see an elevated number of these crashes on Play Console even when Sentry NDK support is disabled because they are caused by other native libs - and they will not show up on Sentry because Sentry NDK support is required to report these crashes

**Comment by vjoby-wavefin** [comment]
Hello Sentry team, is there an ETA on when we can expect a new version to fix these crashes
currently we have rolled out a release to our users on android without sentry to mitigate crashes but we have new features waiting to rollout and we are reluctant to roll them out without sentry.

**Comment by kahest** [comment]
Hey @vjoby-wavefin - thanks for writing in! We don't have an ETA at the moment. We continue to analyse reports coming in but the root cause seems to be located outside of Sentry (see https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1748811364).

Did you try disabling NDK support for the time being? This should prevent Sentry causing these crashes and allows you to still use Sentry for everything else.

**Comment by nkhvorov** [comment]
Hi @kahest and Sentry team!
We're using Sentry for Unity. Thats our crash stats in absolute values per day:
![image](https://github.com/getsentry/sentry-java/assets/138659033/77172f31-319d-417e-b98f-ba206311b8de)

A couple of observations:
1. We see significant increase around 12th of September
2. Only Android 12+ versions are affected. Presumably somehow connected with Google Play System Update from August, as mentioned in this thread aobve
3. We try removing Sentry SDK completely from our build and see crashes going back to stable values
4. We've kept this version for a while without any other updates. Both Android 12-13 and Total crash values are **3-4 times lower after spike than before spike**. Which makes me think either that Sentry have some other issues with stability and causes crashes itself (ironically) or it may be the same reason of Google Play Update rollouted to less OS audience by Google.
5. You mentioned that other libraries might have the same issue, but it seems for us Sentry is the only SDK сausing it for at least 2 of our apps. So it still important issue to fix to not to be blind in case of another crash will raise up

And some follow up questions:
1. Have you analyzed and seen any changelogs in August system update related to your functionality? Like restricting access to some APIs or app tombstones, etc. I see stacktrace in this [issue](https://issuetracker.google.com/issues/300840851) with exception while accessing tombstone.
2. Just curious do you have direct contacts at Google to help you investigate?
> As an intermediate “solution” we added easy ways to disable sentry-native, but be aware that you might see other crashes instead then.
3. Could you please clarify one more time. Do yo mean here that disabling sentry-native would cause another issues instead? Or just that there might be another sdks still causing same issue?

**Comment by seventhmoon** [comment]
For those want to know more about the monthly update on Android (aka mainline), here are some references.

- https://source.android.com/docs/core/ota/modular-system
- https://android-developers.googleblog.com/2023/08/latest-artwork-on-hundreds-of-millions-of-devices.html
- https://android-developers.googleblog.com/2019/05/fresher-os-with-projects-treble-and-mainline.html

**Comment by andersk** [comment]
> > When disabling sentry-native in this way, can you tell us whether that causes libsentry.so to no longer be active in the app?
> 
> Yes, this will prevent `libsentry.so` from being loaded, and thus no native calls being done from the SDK.

@markushi I found that this is not the case. `libsentry.so` is still being loaded with `enableNdk: false`.

```console
panther:/ # dd if=/proc/8363/mem bs=1 skip=507995391806 count=118
/home/runner/work/sentry-java/sentry-java/sentry-android-ndk/sentry-native/external/libunwindstack-ndk/DwarfMemory.cpp118+0 records in
118+0 records out
118 bytes (118 B) copied, 0.009 s, 13 K/s
```

I confirmed this in the source code. `sentryNdkClass` is unconditionally loaded here (`isNdkAvailable` only does a version check):

https://github.com/getsentry/sentry-java/blob/ef25ecb7453ce233d5c7e2fb1d422c99ef510808/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L211-L215

Loading `sentryNdkClass` causes `libsentry.so` to be loaded:

https://github.com/getsentry/sentry-java/blob/ef25ecb7453ce233d5c7e2fb1d422c99ef510808/sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java#L8-L21

Then, `enableNdk` is checked here, after `sentryNdkClass` has already been loaded:

https://github.com/getsentry/sentry-java/blob/ef25ecb7453ce233d5c7e2fb1d422c99ef510808/sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java#L36-L41

So although setting `enableNdk: false` prevents the `init` method from being called, it does not prevent `libsentry.so` from being loaded.

**Comment by chrisbobbe** [comment]
Interesting! Thanks for that investigation @andersk.

Separately, this looked like a promising direction for debugging, for anyone who has bandwidth to pick it up:

> Have you analyzed and seen any changelogs in August system update related to your functionality?

As I mentioned above in https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1737079500, someone has published a [recipe](https://www.esper.io/blog/building-a-google-play-system-update-changelog) to make a detailed changelog between two Google Play system updates. The recipe takes ingredients from real devices. Here are some that can be used:

<details>
<summary>ingredients</summary>

From one device with the July (2023-07-01) Google Play system update (taken from [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.20crashes/near/1643877)):

- `adb shell cmd transparency get module_info -v`: 
[module_info.txt](https://github.com/getsentry/sentry-java/files/12895615/module_info.txt)
- `/apex/apex-info-list.xml` (as a .txt just because GitHub UI errors on upload: "We don't support that file type."): 
[apex-info-list.txt](https://github.com/getsentry/sentry-java/files/12895630/apex-info-list.txt)

From one (different) device with the August (2023-08-01) Google Play system update (taken from [here](https://chat.zulip.org/#narrow/stream/48-mobile/topic/Android.20crashes/near/1643856)):

- `adb shell cmd transparency get module_info -v`: 
[module_info.txt](https://github.com/getsentry/sentry-java/files/12899676/module_info.txt)
- `/apex/apex-info-list.xml` (again as a .txt): 
[apex-info-list.txt](https://github.com/getsentry/sentry-java/files/12899678/apex-info-list.txt)
</details>

It says the process requires well over 100GB of free space for an Android Open Source Project (AOSP) checkout.

**Comment by markushi** [comment]
@nkhvorov Thanks for providing some detailed observations - highly appreciated!
Regarding your questions:
1. We recently tried to dive through the changelog, unfortunately the tags for the August update weren't published back then. Let me double check on this, maybe they were pushed together with the Android 14 release.
2. Yes, we are in direct contact with the engineering folks from Google. I can't share too much details here, but we're investigating on both sides!
3. We see *some* customer reports where the app crashes even when sentry-native is removed. E.g. instead of the stack trace showing libsentry.so, it will render a stack trace with libfbjni.so or libhermes.so (both from RN). This is due to the nature of how a stack corruption is handled, as it doesn't show you the culprit but rather the moment the corruption was detected.

**Comment by markushi** [comment]
@andersk Yes, that's right - thanks for clarifying! If you have access to your `build.gradle` file you can exclude our ndk dependency - that even prevents `sentry-native` from being packaged and thus it won't be loaded.
```kotlin
configurations.configureEach {
  exclude(group = "io.sentry", module = "sentry-android-ndk")
}
```
[See our docs](https://docs.sentry.io/platforms/android/configuration/using-ndk/#using-the-sdk-without-the-ndk) for more details. Now I'm wondering: do you still see a number of elevated crashes when `libsentry.so` is loaded but `init()` is not called?

@chrisbobbe Yes, we already looked into this, unfortunately the tags for the Play System August weren't published up until recently - let me double check on this.

**Comment by markushi** [comment]
Adding https://issuetracker.google.com/u/0/issues/302680512 and https://issuetracker.google.com/issues/304071459 for reference here as well, as they deal with a similar issue since the August update - without the Sentry SDK being used.

**Comment by gnprice** [comment]
> do you still see a number of elevated crashes when `libsentry.so` is loaded but `init()` is not called?

Yes, unfortunately. In the Zulip app on Android:

* When we rolled out a version (our v27.213) that disabled Sentry completely, our crash rate plummeted from about 5% (meaning that 5% of DAUs had at least one crash on a given day, as reported by the Play Console) to about 1%.

  Zulip is a React Native app; "disabled Sentry completely" means we didn't call `Sentry.init` from `@sentry/react-native` in JS, didn't apply `sentry.gradle` in our Gradle build script, and didn't include any `<meta-data />` elements for Sentry in our Android manifest. As a result `libsentry.so` was not loaded.

* Then we rolled out — fortunately only to beta — a version (our v27.214) that re-enabled Sentry in the above ways, but set `enableNdk: false` in that `Sentry.init` call in JS. As a result `libsentry.so` is loaded, but `init()` is not called, as @andersk details at https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1762257314 above.

  This brought the crash rate back up to around 5%, and brought us a wave of user reports of crashes. (We then rolled out a new beta, v27.216, that is just like v27.214 but again disables Sentry completely. The crash rate went rapidly back down.)


> you can exclude our ndk dependency - that even prevents `sentry-native` from being packaged and thus it won't be loaded.

Cool, we'll try that. It would be good to have error reporting again.



> 3\. We see _some_ customer reports where the app crashes even when sentry-native is removed.

I'll add that we're seeing this too. I said above that disabling Sentry completely brought our crash rate down from 5% of users each day seeing a given crash (which is catastrophically high) to about 1%. But a daily crash rate of 1% is still elevated: until this August, our crash rate was steady for a long time at 0.3% to 0.4%. It rose to about 1% in the last week of August, then surged to about 5% in mid-September.

The September surge definitely corresponds to when many people first got the August Google Play system update, and I suspect the August rise corresponds to an earlier smaller rollout of the same update. (It definitely doesn't line up with any change we made that would be likely to affect much.)

So I suspect that the ongoing 1% crash rate, with Sentry completely disabled, is due to the same Google Play system update interacting badly with other non-Sentry libraries. Quantitatively, however, the interaction with Sentry was much, much worse, and remained so even with `enableNdk: false`.

**Comment by markushi** [comment]
@gnprice thanks for all the details, much appreciated! This is quite interesting as you're seeing an elevated number of crashes by loading the `.so` file, without ever calling `sentry_init()`. We're not executing any code on-load, which would further narrow down the search space for the root cause.
Any chance you could share some of those crashes you saw in your beta (.so loaded, but without init() called)? You can either post them here or send them to markus.hintersteiner@sentry.io

**Comment by romtsn** [comment]
If anyone would like to give it a try, the AOSP changelog is published here https://mikeng.github.io/aosp.changelog.to/, but I couldn't find anything in the `art/` subproject which is remotely relevant. Seems like the newer tags were not even published, as the latest change I've seen in art is dated Jul 25...

**Comment by chreck** [comment]
We released our react native app on 3th October and having now over 10k active users. We do not see any crashes like before. On Google Play Console we also have no crashes.

We use the setup and version:

`"@sentry/react-native": "^5.10.0",`

In AndroidManifest.xml we set:

```
         <meta-data android:name="io.sentry.ndk.enable" android:value="false" />
> ```

In the Javascript part we setup Sentry like this:

> ```javascript
> 
> Sentry.init({
> 
>   dsn: "https://123456@sentry.io/100",
> 
>   enableNdk: false,
> 
> })
> ```

**Comment by TheRogue76** [comment]
> @andersk Yes, that's right - thanks for clarifying! If you have access to your `build.gradle` file you can exclude our ndk dependency - that even prevents `sentry-native` from being packaged and thus it won't be loaded.
> 
> ```kotlin
> configurations.configureEach {
>   exclude(group = "io.sentry", module = "sentry-android-ndk")
> }
> ```
> 
> [See our docs](https://docs.sentry.io/platforms/android/configuration/using-ndk/#using-the-sdk-without-the-ndk) for more details. Now I'm wondering: do you still see a number of elevated crashes when `libsentry.so` is loaded but `init()` is not called?
> 
> @chrisbobbe Yes, we already looked into this, unfortunately the tags for the Play System August weren't published up until recently - let me double check on this.

I have had thischange in production for about two days now. The crashes have stabilised, and i am not seeing anything new in Google play store console. Even though most of the issues had mentions of other libraries, i feel like It was a cascading issue and they might have still originated from Sentry's NDK. Before excluding the NDK, i was running on the latest version and had `enableNDK` prop set to false, but the issues persisted.

**Comment by andrey-vishnitskiy-hypemasters** [comment]
@markushi any updates with the fix?

**Comment by markushi** [comment]
Hey everyone, here’s a quick update from our side:
We’re still looking into this issue, following every lead we receive. So far we’ve been able to identify a scenario where our signal handler appears to be receiving a signal it’s not meant to receive. It’s still unclear why this scenario is happening at all and in we’re in close contact with some Google engineers to further investigate the root cause.

**Comment by Sevyls** [comment]
Any status update to this issue? We consider to remove Sentry from our Android app as crashes increased again.

**Comment by kahest** [comment]
@Sevyls did you try [disabling NDK integration](https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1769134525) or [excluding the NDK module](https://github.com/getsentry/sentry-java/issues/2955#issuecomment-1772254031)? If you did and it didn't prevent these crashes, we'd love to hear from you.

**Comment by kahest** [comment]
Quick update - we have a promising lead into a possible solution that we are currently testing and validating with Google.

**Comment by kahest** [comment]
We just released  [6.33.2-beta.1](https://github.com/getsentry/sentry-java/releases/tag/6.33.2-beta.1) with a fix for this issue. Our tests show very promising results, but we released this as a beta to get some more data. Please try out the beta if you can and let us know the results. 🙏

**Comment by kahest** [comment]
[sentry-react-native 5.13.1-beta.1](https://github.com/getsentry/sentry-react-native/releases/tag/5.13.1-beta.1) is now also available for testing.

**Comment by kahest** [comment]
[sentry-unity 1.7.1-beta.1](https://github.com/getsentry/sentry-unity/releases/tag/1.7.1-beta.1) is now also available for testing.

**Comment by kahest** [comment]
We just released [sentry-java 6.34.0](https://github.com/getsentry/sentry-java/releases/tag/6.34.0), which is the first stable release that includes the fix for this issue. I'm closing this now.

**Comment by kahest** [comment]
[sentry-react-native 5.14.0](https://github.com/getsentry/sentry-react-native/releases/tag/5.14.0) has landed

**Comment by kahest** [comment]
[sentry-unity 1.7.1 is now also available](https://github.com/getsentry/sentry-unity/releases/tag/1.7.1)
