### ISSUE TITLE
Support Spring Boot 4

### ISSUE THREAD

**Issue by alexkops** [getsentry/sentry-java#4669]
### Problem Statement

I'm currently testing my application with [Spring Boot 4.0.0-M2](https://spring.io/blog/2025/08/21/spring-boot-4-0-0-M2-available-now) and with the current sentry gradle plugin  5.9.0 in my build file, I will get the following error on start:
`Could not find class [org.springframework.boot.autoconfigure.web.reactive.function.client.WebClientAutoConfiguration]
`
That's because of the modularisation efforts, the WebClient has it's own module now and the class moved to
[module/spring-boot-webclient/src/main/java/org/springframework/boot/webclient/autoconfigure/WebClientAutoConfiguration.java](https://github.com/spring-projects/spring-boot/blob/303d4910bdc042b68cbd48d1d14523d7fbebc445/module/spring-boot-webclient/src/main/java/org/springframework/boot/webclient/autoconfigure/WebClientAutoConfiguration.java#L59)

It would be great if the Sentry Spring Boot 4 support would be ready by the time the final version is released.

**Comment by adinauer** [comment]
Hello @alexkops thanks for reporting in. We've just recently added modules for Spring Boot 4 / Spring 7 but haven't released them yet. Those are currently targeting the M1 release.

We will soon take a look at targeting the M2 release.

What you're describing should already be taken care of by what we have. We're tracking support in https://github.com/getsentry/sentry-java/issues/4080

Not quite sure yet when we'll do another release, but we can try to get one out soon, just wanted to take a quick look at M2 first. Where I haven't manually tested changes in https://github.com/getsentry/sentry-java/pull/4665

**Comment by adinauer** [comment]
@alexkops, we've just released https://github.com/getsentry/sentry-java/releases/tag/8.21.0 which adds `sentry-spring-boot-4` and `sentry-spring-7`, supporting M2.

Can you please test if this solves the problem?

**Comment by alexkops** [comment]
Hmm, maybe you can give me a hint on how to properly test it. The only Sentry dependency I have in my gradle build file is usually `id("io.sentry.jvm.gradle") version "5.9.0"`
But that doesn't reliably load the latest version as I found.
So I added 
```
implementation(platform("io.sentry:sentry-bom:8.21.0") )
implementation("io.sentry:sentry-spring-boot-4-starter")
```
But the error still appears, probably because I also have still `io-sentry-spring-boot-jakarta:8.21.0` in my classpath, as I see in IntelliJ. I guess that is brought in by the gradle plugin.
After commenting out the gradle plugin and the configuration I use it for, it works.
Is there any way to make the gradle plugin use the correct version?

**Comment by lcian** [comment]
Hey @alexkops, yep I just checked and it seems the Gradle plugin still tries to bring in `io-sentry-spring-boot-jakarta` causing the failure. We'll look into this and provide a fix.

**Comment by adinauer** [comment]
@alexkops we've released https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/5.11.0 which should fix the problem with auto intall. It should now install dependencies for Spring Boot 4 / Spring 7 and no longer install modules for Spring Boot 3 / Spring 6.

**Comment by adinauer** [comment]
Closing this as it should be fixed now. Feel free to reopen if needed. We'll update https://github.com/getsentry/sentry-java/issues/4080 with progress on Spring Boot 4 / Spring 7 support.
